### ISSUE TITLE
[Missing Doc Strings]

### ISSUE THREAD

**Issue by sara-02** [deniederhut/niacin#18]
In case there are left out on purpose, the following 2 functions are currently missing doc-strings:

- [ ] https://github.com/deniederhut/niacin/blob/master/niacin/text/word.py#L30

- [ ] https://github.com/deniederhut/niacin/blob/master/niacin/text/char.py#L40

**Comment by deniederhut** [comment]
So I hadn't written docstrings for these since they are private functions of the module, but more documentation is better than less documentation 😄
