### ISSUE TITLE
add_synonym systematically convert "was" into "wa"

### ISSUE THREAD

**Issue by fabiencro** [deniederhut/niacin#39]
As per the title, when using add_synonyms, and whatever probability is used, any occurence of "was" in the input is converted to "wa".

To reproduce:
```python
!pip install niacin

from niacin.text import en
en.word.add_synonyms("he was fine", p=0.00001)

--> Output: 'he wa fine'
```

**Comment by deniederhut** [comment]
Thanks for the bug report!
